language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: G33WvIN7swJ8RxMF6JmrnEGvgacvPxei1EPw4sBC00FUQMUVCY3TI21VYj1/FSNwKoHvDVZGEUcGjPAik5pp0YSRMNKmF/8hnvcp2yv5WkLF1PEPKeEiPRB2NmwJaO/cPJ0nxFbv6ganwUQDQfIm2cHjthQkTCeaWv4opcJdgNEzu+O9yCg8UMuVu0Li3MnbknZl83d5i2+hft8k+V7GBu5wBjxh/v6+oeiPioMpYcLIt++URWO/oDHVkQ19cYvnQLsRkufYD5GlufRHF4muWZSiH7RurPNmaZTIRinJxaIc1Wi5ZSZDRNisUdjUvj7DukFx3ScdDNSOSN4WUn848iMni/p2u9hUwixagF0VEQ9r0VQ9EPclCxhPSFqcN7xEp2/ScOr7FScif9R6uH6T9Y6aqv4wGywIScTnZqFDA8CmWzUIBdSIoi52cyzIzRT4DjPU8IoX3aegfRtbU/OpKyFj1OCG/3YMDosddZVu6ahjmg6J+my+IMeZAewjNa3Tq9z4yCwecTgyVyCj3g/n0CGkBzTPhglkD3rVKOUObqiLdXUHC3BkSjkpDtM7qvod0LVddcPFlX+hJ+I7YkRogw6f1xd2hkN6catzLrg0V8eTYOGV4XS37yWz+VA7U++ax4XjLqH87JPT+XPRoqliOG6B8Rn0mAqG6xCfIUR2ib0=
  app: gespizzav2
  on:
    repo: nzodalandry/lpa2_nzoda
