env:
  global:
    - CC_TEST_REPORTER_ID=144d2977b7deb601e003ece0f9e005fb232ac0b268ba327163990102ed495a38
language: ruby
rvm:
- 2.4.4
deploy:
  run: "rails db:migrate"
  provider: heroku
  api_key:
    secure: wBgdgE6utlPLbgEZ7qakyP/3xqc6V9pV/fmZoHk/XhoO4Qjd21oruaChkDMT8NuqYHaJb2414xPf1kOQI9ZTGnFJg5Xnd6ZXnqlkconzwzRmijgRYgqgyQ9IVaXEvAAvLP/n0juYulgaT8ZD6HhhWPUu+/ZSGgsLvorl22tNeLykyxXGPErTH3pCJzzyAuAlrRTqcxKv3V5hYPuNLi9UJCQ+RK055Zp8w1+oQyc3lrLhvW83FXspyhFsCfM9Z0fWMF3XjiE1i9K8CpOho6Q3jPO5kIH9kbXreM7m2wvwpUEHT2a+KDhtuHrd+YVf0qcszgZdpbJhbR8T94atc4sRYXLNF7XsWLv8DSKoCNPaB+Vm7xTIM5hNBjBglTqcMJG+OX7L+N3zhQLXQIE1hmCnHFD1T9NIxTjOFTxf1zGaVyFzpy3yn7RjroL9Y1hnrdx8Oxoh+IYCX7xx+XeIINCTXQ/nxq2M6vmKs2qH2spU3KHopbiIfJzwn+fZ+sAz0pkJ4tvNpR31jeigpKP8lv4qZ0KTflPELgV+e40tYSlErFR0eCIQGWpitmMUeJ32khXUj1W/S14oP6EVYs7dkhsVzY/seJ6iGIGFb+CqA11V3s6WHx6yoVZL67OFhBCLj9iH3ZAoW4574JPBv3qBkwobbl96i+8LTCxTFAqDM9iA2nI=
  app: gespizzav2
  on:
    repo: nzodalandry/lpa2_nzoda
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT